import type { Config } from 'tailwindcss'

// Design tokens ported from new_design/DESIGN.md ("XO Edu Lab Design System" — Space to Become).
export default <Partial<Config>>{
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        tertiary: '#0f0800',
        'inverse-on-surface': '#ecf0ff',
        secondary: '#116c46',
        'on-tertiary-container': '#a78237',
        'primary-fixed': '#d9e2fc',
        'error-container': '#ffdad6',
        'on-background': '#111c2d',
        'primary-container': '#172033',
        'surface-dim': '#d0daf2',
        'surface-variant': '#d9e3fb',
        'on-surface': '#111c2d',
        'surface-tint': '#555e74',
        'on-secondary': '#ffffff',
        'secondary-fixed-dim': '#85d7a9',
        'surface-container-low': '#f0f3ff',
        'inverse-surface': '#273143',
        outline: '#76777d',
        'primary-fixed-dim': '#bdc6e0',
        'outline-variant': '#c6c6cd',
        'secondary-container': '#9ef1c1',
        'tertiary-fixed': '#ffdea6',
        'on-secondary-container': '#18704a',
        'surface-container-lowest': '#ffffff',
        'surface-container-high': '#dfe8ff',
        'on-surface-variant': '#45474c',
        'inverse-primary': '#bdc6e0',
        'on-primary-container': '#7f879f',
        primary: '#172033',
        background: '#f9f9ff',
        'on-error-container': '#93000a',
        surface: '#f9f9ff',
        'secondary-fixed': '#a1f4c4',
        'on-primary-fixed': '#121b2e',
        'surface-container-highest': '#d9e3fb',
        'on-secondary-fixed': '#002112',
        'surface-container': '#e8eeff',
        error: '#ba1a1a',
        'tertiary-fixed-dim': '#ecc06e',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed-variant': '#005233',
        'on-primary': '#ffffff',
        'on-error': '#ffffff',
        'on-tertiary-fixed': '#271900',
        'tertiary-container': '#2d1e00',
        'on-primary-fixed-variant': '#3e475b',
        'surface-bright': '#f9f9ff',
        'on-tertiary-fixed-variant': '#5d4200',
        // Not in the raw token dump but called for by the DESIGN.md prose
        // ("Gold is reserved for highlights, achievement states, and premium features").
        gold: '#d8ae5e',
        canvas: '#f7f7f2',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '24px',
        full: '9999px',
      },
      spacing: {
        base: '8px',
        'max-width': '1280px',
        xs: '4px',
        sm: '12px',
        lg: '48px',
        'margin-mobile': '20px',
        gutter: '24px',
        xl: '80px',
        md: '24px',
        'margin-desktop': '64px',
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        serif: ['Newsreader', 'serif'],
        'headline-lg-mobile': ['Newsreader'],
        'display-lg': ['Newsreader'],
        'label-sm': ['"Plus Jakarta Sans"'],
        'headline-md': ['Newsreader'],
        'body-lg': ['"Plus Jakarta Sans"'],
        'body-md': ['"Plus Jakarta Sans"'],
        'headline-lg': ['Newsreader'],
        'headline-sm': ['"Plus Jakarta Sans"'],
        'label-md': ['"Plus Jakarta Sans"'],
      },
      fontSize: {
        'headline-lg-mobile': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'display-lg': ['64px', { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['40px', { lineHeight: '48px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
      },
    },
  },
}
